plugins {
    id("java")
    // Shadow bundles your code into one jar. FarmersDelight + CraftEngine are NOT bundled (compileOnly).
    id("io.github.goooler.shadow") version "8.1.7"
}

group = "com.example.fdaddon"
version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.momirealms.net/releases/") // CraftEngine
    mavenLocal()
}

// The FarmersDelight api.** facade jar is prebuilt (from the closed-source FarmersDelight repo's :apiJar
// task) and committed into libs/, so this addon builds without any access to the FarmersDelight source.
// When the main plugin publishes a new API, replace libs/farmersdelight-api.jar and bump the version.

// Builds FarmersDelight's :apiJar through the composite build and stages it into libs/, so this addon
// always compiles against the current api.** facade. Requires ../FarmersDelight to be checked out
// alongside this repository (CI does that too).
val syncFarmersDelightApi by tasks.registering(Copy::class) {
    group = "build"
    description = "Builds farmersdelight :apiJar via composite build and stages it into libs/."
    dependsOn(gradle.includedBuild("farmersdelight-plugin").task(":apiJar"))
    from(file("../FarmersDelight/build/libs")) {
        include("farmersdelight-plugin-*-api.jar")
        rename { "farmersdelight-api.jar" }
    }
    into("libs")
}

tasks.compileJava { dependsOn(syncFarmersDelightApi) }

// CraftEngine is resolved from Maven. Overridable so a compatibility check can build the same sources
// against another release without editing this file:  gradlew build -PceVersion=26.8.2
val ceVersion = providers.gradleProperty("ceVersion").getOrElse("26.9.1")

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
    compileOnly("org.jetbrains:annotations:26.1.0")

    // CraftEngine from the official Maven repository.
    compileOnly("net.momirealms:craft-engine-bukkit:$ceVersion")
    // The bukkit artifact no longer bundles core, so the core classes come from their own jar.
    compileOnly("net.momirealms:craft-engine-core:$ceVersion")

    // Compile against the API-only JAR generated by the included FarmersDelight build.
    // Only api packages retain stable names after obfuscation; the server plugin supplies their implementation.
    compileOnly(files("libs/farmersdelight-api.jar"))
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release.set(21)
}

tasks.processResources {
    filteringCharset = "UTF-8"
    filesMatching("paper-plugin.yml") { expand("version" to version) }
}

tasks.shadowJar {
    archiveBaseName.set("fdaddontemplate")
    // Drop Shadow's default "-all" classifier so the artifact is the plain documented file name.
    archiveClassifier.set("")
}

tasks.jar { enabled = false }
tasks.build { dependsOn(tasks.shadowJar) }
